# fly.toml app configuration file generated for jpfastapi on 2023-11-06T20:40:48-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jpfastapi"
primary_region = "gig"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
